
N_ACTIONS = 8
N_CAMERA_DIRECTIONS = 4 

SCREEN_WIDTH = 2*80 
SCREEN_HEIGHT = 2*60 
CENTER_X = SCREEN_WIDTH/2
CENTER_Y = SCREEN_HEIGHT/2
BALL_SIZE_MIN = SCREEN_HEIGHT/10
BALL_SIZE_MAX = SCREEN_HEIGHT/3
